# Generated by Django 5.1.5 on 2025-03-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_house_id_house__id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
