# Generated by Django 5.1.5 on 2025-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_chatroom_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('Buyer', 'Buyer'), ('seller', 'Seller')], default='Buyer', max_length=20),
        ),
    ]
