# Generated by Django 5.1.5 on 2025-03-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
