# Generated by Django 5.1.5 on 2025-03-25 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_house_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.house'),
        ),
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller', 'house')},
        ),
    ]
