# Generated by Django 5.1.5 on 2025-03-25 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_chatroom_buyer_alter_chatroom_seller_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='room',
            new_name='chat_room',
        ),
    ]
