# Generated by Django 5.1.5 on 2025-03-25 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_room_message_chat_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='room',
        ),
    ]
