# Generated by Django 5.1.5 on 2025-03-26 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_order_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='paypal_account_id',
            field=models.CharField(blank=True, help_text="Seller's PayPal account ID (Email or PayPal ID)", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('buyer', 'Buyer'), ('seller', 'Seller')], default='buyer', max_length=20),
        ),
    ]
