# Generated by Django 5.1.5 on 2025-03-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_order_paidat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chatroom',
            unique_together={('buyer', 'seller')},
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='house',
        ),
    ]
